import { PropsWithChildren } from 'react';
import type { Metadata } from 'next';

import { Analytics } from '@vercel/analytics/react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang='en'>
      <body>
        <div >
          <main >
            <div>{children}</div>
          </main>
        </div>
        <Analytics />
      </body>
    </html>
  );
}