import { PropsWithChildren } from 'react';
import type { Metadata } from 'next';

import { Button } from '@/components/ui/button';
import { logout } from '@/features/auth/actions/auth-actions';
import { Analytics } from '@vercel/analytics/react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang='en'>
      <body>
        <div>
          <form action={logout}>
            <Button>Log out</Button>
          </form>
        </div>
        <div >
          <main >
            <div>{children}</div>
          </main>
        </div>
        <Analytics />
      </body>
    </html>
  );
}